redis:
    image: redis
db:
    image: postgres:9.4
    environement:
        - POSTGRES_HOST_AUTH_METHOD=trust
vote:
    image: prajwal/vote-app
    port:
        - 5000:80
    links:
        - redis:redis
result:
    image: prajwal/result-app
    port:
        - 5001:80
    links:
        - redis:redis
        - db:db
worker:
    image: prajwal/worker-app
    links:
        - redis:redis
        - db:db